PACKAGE = indexhtml
VERSION = 2014.0
DATE = `date +%Y%m%d`

all:

clean:
	-find . -name '*~' | xargs rm -f
	rm -f *.bz2

install:
	mkdir -p $(RPM_BUILD_ROOT)/usr/share/doc/HTML
	cp -rp HTML/* $(RPM_BUILD_ROOT)/usr/share/doc/HTML/

version:
	@echo $(VERSION)

# rules to build a test rpm

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.xz

localcopy:
	git archive --prefix=$(PACKAGE)-$(VERSION)/ HEAD | xz -c -T0 > $(PACKAGE)-$(VERSION).tar.xz

# rules to build a distributable rpm

dist: cleandist localcopy

log: changelog

changelog: ../common/username.xml
	svn2cl --authors ../common/username.xml --accum
	rm -f ChangeLog.bak
	svn commit -m "Generated by svn2cl the `LC_TIME=C date '+%d_%b'`" ChangeLog

# Makefile ends here
