PACKAGE = indexhtml
VERSION = 2013.0
DATE = `date +%Y%m%d`

SVN_URL  := $(shell svn info | grep ^URL: | cut -f2 -d\ )
SVN_BASE := $(shell svn info | sed -n '/^URL: \(.*\/$(PACKAGE)\).*/s//\1/p')

all:

clean:
	-find . -name '*~' | xargs rm -f
	rm -f *.bz2

install:
	mkdir -p $(RPM_BUILD_ROOT)/usr/share/doc/HTML
	cp -p HTML/* $(RPM_BUILD_ROOT)/usr/share/doc/HTML/

version:
	@echo $(VERSION)

# rules to build a test rpm

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

localcopy:
	git export -q . $(PACKAGE)-$(VERSION)

tar:
	tar cvf $(PACKAGE)-$(VERSION).$(DATE).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).$(DATE).tar
	rm -rf $(PACKAGE)-$(VERSION)


# rules to build a distributable rpm

dist: cleandist localcopy tar

log: changelog

changelog: ../common/username.xml
	svn2cl --authors ../common/username.xml --accum
	rm -f ChangeLog.bak
	svn commit -m "Generated by svn2cl the `LC_TIME=C date '+%d_%b'`" ChangeLog

# Makefile ends here
